name: release

on:
  workflow_run:
    workflows: [tests]
    branches: [release]
    types: [completed]

concurrency:
  group: release
  cancel-in-progress: true

jobs:

  setup:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: 'release'
        fetch-depth: 2

    - name: Prepare to build
      run: pip install build

    - name: Build sdist
      run: python -m build --sdist

    - uses: actions/upload-artifact@main
      with:
        name: dist-no-wheels
        path: dist/*.tar.*

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:

      - name: Download a distribution artifact
        uses: actions/download-artifact@main
        with:
          path: dist
          pattern: dist-*
          merge-multiple: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:

    - name: Notify Success
      uses: archive/github-actions-slack@master
      with:
          slack-channel: C2CRL4C4V
          slack-text: "*[${{ github.repository }}]* package is published *(${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-optional-as_user: false
          slack-optional-icon_emoji: ":white_check_mark:"
